# Generated by Django 2.0 on 2017-12-29 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20171229_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsanaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsanaTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsanaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='group',
            name='managers',
            field=models.ManyToManyField(related_name='group_managers', to='bot.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='gropu_members', to='bot.User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='managers',
            field=models.ManyToManyField(related_name='task_managers', to='bot.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='asana_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.AsanaTeam'),
        ),
        migrations.AddField(
            model_name='group',
            name='line_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.LineGroup'),
        ),
        migrations.AddField(
            model_name='task',
            name='asana_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.AsanaTask'),
        ),
        migrations.AddField(
            model_name='user',
            name='asana_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.AsanaUser'),
        ),
        migrations.AddField(
            model_name='user',
            name='line_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.LineUser'),
        ),
    ]
