# Generated by Django 2.0 on 2017-12-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20171229_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='bot.User'),
        ),
    ]
