# Generated by Django 2.0 on 2017-12-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20171229_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linegroup',
            name='name',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='authority',
            field=models.IntegerField(choices=[(0, 'Master'), (1, 'Editor'), (2, 'Watcher')], max_length=64),
        ),
    ]
