# Generated by Django 2.0 on 2017-12-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20171229_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authority',
            field=models.IntegerField(choices=[(0, 'Master'), (1, 'Editor'), (2, 'Watcher')]),
        ),
    ]
