# Generated by Django 2.0 on 2017-12-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20171230_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='group_participants',
            new_name='groups',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_participants',
        ),
        migrations.AddField(
            model_name='task',
            name='participants',
            field=models.ManyToManyField(related_name='belonging_tasks', to='bot.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='managers',
            field=models.ManyToManyField(related_name='managing_groups', to='bot.User'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='belonging_groups', to='bot.User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='managers',
            field=models.ManyToManyField(related_name='managing_tasks', to='bot.User'),
        ),
    ]
