# Generated by Django 2.0 on 2017-12-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_task_is_participate_all_in_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='名無しのグループ', max_length=64),
            preserve_default=False,
        ),
    ]
