# Generated by Django 2.0 on 2017-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20171230_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='groups',
            field=models.ManyToManyField(related_name='tasks', to='bot.Group'),
        ),
    ]
