# Generated by Django 2.0 on 2018-01-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20171230_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_participate_all_in_groups',
        ),
    ]
