# Generated by Django 2.0 on 2018-01-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_remove_task_is_participate_all_in_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('High', 'High'), ('Middle', 'Middle'), ('Low', 'Low')], default='Middle', max_length=16),
        ),
    ]
