# Generated by Django 2.0 on 2018-01-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20180103_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskJoinCheckJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.PositiveIntegerField()),
                ('deadline', models.DateTimeField()),
                ('checked_users', models.ManyToManyField(related_name='checked_task_join_check_job', to='bot.User')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_checks', to='bot.Group')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='absent_members',
            field=models.ManyToManyField(related_name='absent_tasks', to='bot.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='joinable_members',
            field=models.ManyToManyField(related_name='joinable_tasks', to='bot.User'),
        ),
        migrations.AddField(
            model_name='taskjoincheckjob',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.Task'),
        ),
    ]
