# Generated by Django 2.0 on 2018-11-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20180105_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=64, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='discord_server',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.DiscordServer'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.DiscordUser'),
        ),
    ]
