# Generated by Django 2.0 on 2018-11-14 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_auto_20181112_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LINEGroup', 'LINEGroup'), ('DiscordServer', 'DiscordServer'), ('DiscordChannel', 'DiscordChannel'), ('AsanaTeam', 'AsanaTeam')], max_length=16)),
                ('id_in_service', models.CharField(max_length=64)),
                ('belonging_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_groups', to='bot.Group')),
            ],
        ),
    ]
