# Generated by Django 2.0 on 2018-11-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_servicegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegroup',
            name='name_in_service',
            field=models.CharField(default='不明', max_length=64),
            preserve_default=False,
        ),
    ]
