# Generated by Django 2.0 on 2018-11-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_servicegroup_name_in_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='asana_team',
        ),
        migrations.RemoveField(
            model_name='group',
            name='discord_server',
        ),
        migrations.RemoveField(
            model_name='group',
            name='line_group',
        ),
        migrations.DeleteModel(
            name='AsanaTeam',
        ),
        migrations.DeleteModel(
            name='DiscordServer',
        ),
        migrations.DeleteModel(
            name='LineGroup',
        ),
    ]
