# Generated by Django 2.0 on 2018-11-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20181115_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LINEUser', 'LINEUser'), ('DiscordUser', 'DiscordUser'), ('AsanaUser', 'AsanaUser')], max_length=16)),
                ('id_in_service', models.CharField(max_length=64)),
                ('name_in_service', models.CharField(max_length=64)),
                ('belonging_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_users', to='bot.User')),
            ],
        ),
    ]
