# Generated by Django 2.0 on 2018-11-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_serviceuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='asana_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discord_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='line_user',
        ),
        migrations.DeleteModel(
            name='AsanaUser',
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
        migrations.DeleteModel(
            name='LineUser',
        ),
    ]
